ALTER TABLE hooptie
RENAME ТО car_table,
ALTER TABLE car_table
ADD COLUMN carJd INT NOT NULL AUTO_INCREMENT FIRST,
ADD PRIMARY KEY (car_id),
ADD COLUMN VIN VARCHAR(16) SECOND,
CHANGE COLUMN mo_model VARCHAR(20),
MODIFY COLUMN color ALTER model,
MODIFY COLUMN year SIXTH,
CHANGE COLUMN howmuch_price DECIMAL(7,2);